### ISSUE TITLE
Auto Size

### ISSUE THREAD

**Issue by bernardogeneroso** [sveinungf/spreadcheetah#12]
Hi again! Thank you for the alignment.
I didn't find auto size on documentation related with columns.

**Comment by sveinungf** [comment]
Auto sizing column width isn't supported, and unfortunately it might never be fully supported. This is because XLSX files don't have support for it, only the actual column width values are stored. The way Excel and other spreadsheet libraries do auto sizing is by going through the data in each column and then calculate the width. However, this requires having all the row data in memory, and SpreadCheetah is designed to avoid that for performance reasons. So the only option for now is to set the width explicitly for each column.

**Comment by bernardogeneroso** [comment]
I understand, thank you.
