### ISSUE TITLE
Why are all types in the CellReferences namespace internal?

### ISSUE THREAD

**Issue by jzabroski** [sveinungf/spreadcheetah#56]
I am guessing the reason has something to do with code generation, but I'm sure you have a much deeper understanding of your architecture decisions than I do.

My initial thought is I'd like to be able to work with cell references directly, especially cell ranges, and to have convenience properties on ranges like FirstRow, FirstColumn, LastRow, LastColumn, But, if features like #55 are implemented using internal tools, then this is probably not needed for me/by me.  I'm just used to using commercial libraries where I can easily do these things.

**Comment by sveinungf** [comment]
The types are internal because I will most likely make fundamental changes to them at some point. If they were public I wouldn't be able to do that without causing a breaking change.

When working with references they should sometimes be for single cells, sometimes for cell ranges, and sometimes both. Sometimes they should be relative references, sometimes absolute references, and sometimes both. I haven't yet found a way to represent all these options that I think would be good enough to expose publicly.

**Comment by jzabroski** [comment]
That's fine.

Impressive library. Would love to chat about it sometime on WhatsApp or discord.
